POST http://localhost:8080/api/auth/reset-password-confirm HTTP/1.1
Content-Type: application/json;

{
    "token":"Bearer20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2xvazIiLCJleHAiOjE3MjYyOTAyNDh9.5Qxrw3X7TsmJ7gv7be0_M0RTgWYY3JKmh92jmAcPylc",
    "newPassword": "FHRfhrdl2@"
}